.markdownlint.json
en/contribution.md
package-lock.json

This initial merge modifies the structure of the initial commit to a format closer to TBS Standards.
The content has also been modified to better reflect the approach we're trying to take.

Modify structure and expand content

---

en/contribution.md
package.json

* Review requirements
* Add questions re: Protected Information
* Fix markdown
* Fix package.json

Update Develop Branch

---

en/contribution.md
fr/contribution.md
package.json

* Update requirements based on legal feedback
* Remove sections that will be studied later
* Start French version

Update requirements and structure

---

README.md
en/guides/using-open-source-software.md

This PR adds a reference to the Directive on Management of Information Technology to the README and clarifies the language around the prioritization of the use of open-source software.
In the past, I've wondered how to interpret the above-mentioned directive (e.g. if I want to stop using Oracle DB in my app, then do I need to treat open-source relational databases with priority?). I was pleased to see in the "Requirements" section that the answer is yes, and I thought it was important to make that information explicit in the guide as well.
Please see the individual commit messages in this PR for more details.

Clarify language re. prioritization of OSS

---

en/guides/publishing-open-source-code.md

Alternatively, this could just be a single line at the bottom of the table. It's ultimately the same process whatever license you pick.

Filling in the howto & trying to span the table.

---

cspell.json
en/guides/contributing-to-open-source-software.md
en/guides/publishing-open-source-code.md
en/guides/using-open-source-software.md

Update guidelines based on Policy and Planning review:
* Using open source software
* Contributing to 3rd party OSS
* Publishing OSS

Pnp review

---

en/guides/contributing-to-open-source-software.md

Add a CLA and DCO info section and guidance

Add CLA and DCO info

---

en/guides/contributing-to-open-source-software.md

Matches the text from Directive on Management of Information Technology

typo: licenses -> license

---

en/open-source-standards.md

Makes it a little easier to sync text suggestions from Word

chore: format details/summary

---

en/open-source-standards.md

GitHub was happy, but GitHub pages doesn't render correctly

Revert "chore: format details/summary"

---

README.md
en/guides/prior-to-starting.md
en/guides/publishing-open-source-code.md
en/open-source-standards.md

@ShadeWyrm leaving this to the side for now as we're meeting tomorrow and I don't want to mix it up. I've left it split up for easier cherry-picking of parts. Some conflicted since it was off an older draft so there are a few parts missing from Concept Case

Internal feedback

---

.gitignore
404.html
Gemfile
_config.yml
_data/i18n/general.yml
_includes/breadcrumbs.html
_includes/footer.html
_includes/head.html
_includes/header.html
_layouts/default.html
assets/style.css
index.html

Navigation/menu is still broken.
Took an older copy from ORE-ERO, then tried updating it so there may be some

Jekyll theme from GCWeb/CDTS

---

en/guides/publishing-open-source-code.md

I made a quick change. This fixes #69 and align with SPDX id for GPL licences.

Fix recomended GPL licences for GC

---

en/guides/using-open-source-software.md

Fix sentence typo

---

Gemfile
_config.yml
_data/i18n/general.yml
_includes/breadcrumbs.html
_includes/header.html

fix: Add new files to navigation

---

en/guides/using-open-source-software.md
en/open-source-standards.md

Could also rephrase 
**Wherever possible, use open source software without modification or contribute back to the project.**
==>
**Wherever possible, use open source software without modification or contribute back to them.**
The second is closer to the original wording, but the first sounds more precise. Though I suppose the different between the two liste here is stylistic.

Minor typo / phrasing issue

---

_data/i18n/general.yml

Hi,
This tiny PR will fix : 
- 1 typo in `_data/i18n/general.yml`
Bye! :robot:

Fix typo in _data/i18n/general.yml

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/general.md
.github/dependabot.yml
.github/workflows/cspell-problem-matcher.json
.github/workflows/cspell.yml
.github/workflows/link-check.yml
.github/workflows/markdownlint-problem-matcher.json
.github/workflows/markdownlint.yml
.travis.yml
README.md
_config.yml

---
name: General
about: This a gerneral pull request template to be used for any reason
title: ''
labels: ''
assignees: ''
---

chore: Sync CI setup from Template repo

---

.github/workflows/cspell.yml
.github/workflows/link-check.yml
.github/workflows/markdownlint.yml

---
name: General
about: This a gerneral pull request template to be used for any reason
title: ''
labels: ''
assignees: ''
---

ci: use setup-node v3

---

en/guides/publishing-open-source-code.md
fr/guides/publication-code-source-ouvert.md

update copyright text
